### ISSUE TITLE
Crash if wild feverstone horse is hit

### ISSUE THREAD

**Issue by HawkeTheKite** [XurxoMF/DontHitYourPets#1]
Playing on single player world opened online with 3 friends. Horses do not take damage from arrows, they bounce off which I assumed was because of Don't Hit Your Pets despite horses being untamed. However when a horse is ridden into a campfire or if a wild (never fed, completely wild) horse is hit with melee (tested with a punch) my (host) game crashes but none of the other players are crashed. Will be testing on true single player later.

Seems to be an issue interacting between don't hit your pets and petai
Reporting to both just in case 

Crash report in logs:
1/5/2024 1:44:38 AM: Critical error occurred in the following mod: petai@2.2.0
Loaded Mods: driftersbelongunderground@1.0.1, caninae@1.0.7, primitivesurvival@3.4.5, game@1.19.0-rc.4, accessibilitytweaks@3.4.1, animalcages@3.0.0, animationmanagerlib@0.2.0, BedRespawning@1.0.1, carryon@1.7.0-pre.3, coolinbarrel@0.5.3, hudclock@3.4.0, moreanimals@1.3.1, mouse4and5@1.0.0, petai@2.2.0, creative@1.19.0-rc.4, survival@1.19.0-rc.4, cats@2.0.0, feverstonehorses@1.6.0-rc.2, feverstonewilds@1.4.5, tieredtradebags@1.0.1, wolftaming@2.0.1
System.MissingMethodException: Method not found: 'Boolean PetAI.PetConfig.get_pvpOff()'.
at DontHitYourPets.HarmonyPatches.DontHitYourPetsPatch.Prefix(EntityPet __instance, Boolean& __result, DamageSource damageSource, Single damage)
at PetAI.EntityPet.ShouldReceiveDamage_Patch1(EntityPet this, DamageSource damageSource, Single damage)
at PetAI.EntityMount.ShouldReceiveDamage(DamageSource damageSource, Single damage) in E:\Workspace\vintage_story_mods\petai\src\Entity\EntityMount.cs:line 106
at Vintagestory.API.Common.Entities.Entity.ReceiveDamage(DamageSource damageSource, Single damage) in VintagestoryApi\Common\Entity\Entity.cs:line 806
at Vintagestory.API.Common.EntityAgent.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 284
at PetAI.EntityMount.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode) in E:\Workspace\vintage_story_mods\petai\src\Entity\EntityMount.cs:line 96
at Vintagestory.Client.NoObf.ClientMain.TryAttackEntity(EntitySelection selection) in VintagestoryLib\Client\ClientMain.cs:line 2684
at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 393
at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 96
at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1006
at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
at OpenTK.Windowing.Desktop.GameWindow.Run()
at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by XurxoMF** [comment]
Hi, thx a lot for the report. I've only tested it with petai and wolf taming.
For now on I've to wait for petai author(Gerste) to upload a stable version of the mod. Once he upload it I'll fix it(or try to) and upload a fix ^^

EDIT: I could fix it now but with work I've almost no time, sorry ;-;

**Comment by XurxoMF** [comment]
Are you playing on 1.19 or 1.18.15?

**Comment by XurxoMF** [comment]
Fixed, Gerste changed a config name from pvpOff to PvpOff and pucked up the patches XD

**Comment by XurxoMF** [comment]
Fixed, Gerste changed a config name from pvpOff to PvpOff and pucked up the patches XD

**Comment by HawkeTheKite** [comment]
at Vintagestory.Server.ServerMain.Process() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 881
12.1.2024 19:21:19 [Server Warning] Exception at client 1. Disconnecting client.
12.1.2024 19:21:19 [Server Event] Player Xyconis got removed. Reason: Threw an exception at the server
12.1.2024 19:21:19 [Server Error] System.MissingMethodException: Method not found: 'Boolean PetAI.PetConfig.get_PvpOff()'.
Still exists in the most recent version and still not sure why wild (never fed) horses are protected

**Comment by XurxoMF** [comment]
>  at Vintagestory.Server.ServerMain.Process() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 881
> 12.1.2024 19:21:19 [Server Warning] Exception at client 1. Disconnecting client.
> 12.1.2024 19:21:19 [Server Event] Player Xyconis got removed. Reason: Threw an exception at the server
> 12.1.2024 19:21:19 [Server Error] System.MissingMethodException: Method not found: 'Boolean PetAI.PetConfig.get_PvpOff()'.
> Still exists in the most recent version and still not sure why wild (never fed) horses are protected

I'll check it

About the wild horses protected... that may be bc of the way feverston wild spawns them. I'm checking if the PvpOff is enabled and if the animal is in any state different from wild(tammed, half tammed or watever). If the wild horse has any other state than wild it'll be protected... I can't do anything about that, to do it DHYP have to require both mods and not only PetAI.

EDIT: Can you pls tell me the versions of Pet AI and Don't Hit Your Pets you're using? Only 1.19.0 versions of Pet AI are compatible with the new version of Don't Hit Your Pets so if you're using an old version of Pet AI please update it or use the old verion of Don't Hit Your Pets

**Comment by HawkeTheKite** [comment]
The PetAI version may in fact be the issue then, as we're on version 1.8.1! I'll try changing that at next server reset and see if it fixes things! 
Though we're playing 1.18.15 cause the server host we're using (bisect) isn't supporting 1.19 yet

**Comment by XurxoMF** [comment]
I've tested it with last version of Pet AI and Feverston Wilds and it's working fine... You have to use the old version of DHYP for it to work.
